Teme/teme_ses14/Cars_for_sale/Cars/urls.py
from django.urls import path
from . import views
app_name = "cars"
urlpatterns = [
    path("", views.cars, name="all_cars"),
    path("<int:car_id>/", views.car_details, name="car_details"),
    path("car/", views.car_add, name="add")
]

Teme/teme_ses14/Cars_for_sale/Cars_for_sale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Cars/", include("Cars.urls"))
]

Teme/teme_ses14/Cars_for_sale/Cars/models.py
from django.db import models

CAR_MODELS = [
    ("S", "Sport"),
    ("J", "Jeep"),
    ("V", "Van")
]
FUEL = [
    ("diesel", "Diesel"),
    ("electric", "Electric"),
    ("gasoline", "Gasoline")
]


# Create your models here.
class Car(models.Model):
    name = models.CharField(max_length=50)
    year = models.CharField(max_length=30)
    model = models.CharField(max_length=1, choices=CAR_MODELS, null=False)
    fuel = models.CharField(max_length=8, choices=FUEL)

    def __str__(self):
        return f"{self.name} >>> {self.year} >>> {self.model} >>> {self.fuel}"

Teme/teme_ses14/Cars_for_sale/Cars/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Car


# Create your views here.
def index(request):
    return HttpResponse('Welcome')

def cars(request):
    cars_list = Car.objects.all()
    return render(request, "all_cars.html", {"cars": cars_list})

def car_details(request, car_id):
    car = get_object_or_404(Car, pk=car_id)
    return render(request, "car_details.html", {"car": car})

def car_add(request):
    car_data = request.POST.dict()
    try:
        car = Car(
            name = car_data["name"],
            year = car_data["year"],
            model = car_data["model"],
            fuel = car_data["fuel"]
        )
        car.save()
    except KeyError:
        return render(request, "error.html", {"error_message":"Error!"})
    return HttpResponseRedirect(reverse("cars:all_cars"))

Teme/teme_ses14/Cars_for_sale/Cars/templates/add_car_form.html
<form action="{% url 'cars:add' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <label for="name">
            Name:
        </label>
        <input type="text" name="name" id="name">
        <br>
         <label for="year">
            Year:
        </label>
        <input type="text" name="year" id="year">
        <br>
        <label for="model">
            Model:
            <label for="model(S)">
                Sport
            </label>
            <input type="radio" name="model" id="model(S)" value="S">
            <label for="model(J)">
                Jeep
            </label>
            <input type="radio" name="model" id="model(J)" value="J">
            <label for="model(V)">
                Van
            </label>
            <input type="radio" name="model" id="model(V)" value="V">
            <br>
            <label for="fuel">
                Fuel:
            </label>
            <input type="text" name="fuel" id="fuel">
        </label>
    </fieldset>
    <input type="submit" value="ADD">
</form>

Teme/teme_ses14/Cars_for_sale/Cars/templates/all_cars.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cars</title>
</head>
<body>
{% if cars %}
    <ul>
        {% for car in cars %}
            <li>
                <a href="{% url 'cars:car_details' car.id %}">{{car}}</a>
            </li>
        {% endfor %}
    </ul>

{% endif %}
{% include "add_car_form.html" %}
</body>
</html>

Teme/teme_ses14/Cars_for_sale/Cars/templates/car_details.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{car.name}}</title>
</head>
<body>
{{car}}
</body>
</html>

Teme/teme_ses14/Cars_for_sale/Cars/templates/error.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error</title>
</head>
<body>
{{error_message}}
</body>
</html>