Sesiunea14/pet_adoption_agency/pet_adoption_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pets/", include("pets.urls"))
]

Sesiunea14/pet_adoption_agency/pets/urls.py
from django.urls import path
from . import views
app_name = "pets"
urlpatterns = [
    path("", views.pets, name="all_pets"),
    path("<int:pet_id>/", views.pet_details, name="pet_details"),
    path("pet/", views.pet_add, name="add")
]

Sesiunea14/pet_adoption_agency/pets/models.py
from django.db import models

PET_GENDRES = [
    ("F", "Female"),
    ("M", "Male")
]
PET_TYPES = [
    ("cat", "Cat"),
    ("dog", "Dog"),
    ("rabbit", "Rabbit")
]
# Create your models here.

class Pet(models.Model):
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=30)
    gender = models.CharField(max_length=1, choices=PET_GENDRES, null=False)
    species = models.CharField(max_length=6, choices=PET_TYPES)

    def __str__(self):
        return f"{self.name} -> {self.location} -> {self.gender} -> {self.species}"

Sesiunea14/pet_adoption_agency/pets/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Pet


# Create your views here.
def index(request):
    return HttpResponse('Hello World! Here is the pet index')


def pets(request):
    pets_list = Pet.objects.all
    return render(request, "all_pets.html", {"pets": pets_list})

def pet_details(request, pet_id):
    pet = get_object_or_404(Pet, pk=pet_id)
    return render(request, "pet_details.html", {"pet": pet})

def pet_add(request):
    pet_data = request.POST.dict()
    try:
        pet = Pet(
            name = pet_data["name"],
            location = pet_data["location"],
            gender = pet_data["gender"],
            species = pet_data["species"]
        )
        pet.save()
    except KeyError:
        return render(request, "error.html", {"error_message":"Error! Invalid pet details"})
    return HttpResponseRedirect(reverse("pets:all_pets"))

Sesiunea14/pet_adoption_agency/pets/templates/add_pet_form.html
<form action="{% url 'pets:add' %}" method = "post" >
    {% csrf_token %}
    <fieldset>
        <label for="name">
            Name:
        </label>
        <input type="text" name="name" id="name">
        <br>
        <label for="location">
            Location:
        </label>
        <input type="text" name="location" id="location">
        <br>
        <label for="gender">
            Gender:
        </label>
        <label for="gender(F)">
            Female
        </label>
        <input type="radio" name="gender" id="gender(F)" value="F">
        <label for="gender(M)">
            Male
        </label>
        <input type="radio" name="gender" id="gender(M)" value="M">
        <br>
        <label for="species">
            Specie:
        </label>
        <input type="text" name="species" id="species">
    </fieldset>
    <input type="submit" value="ADD">
</form>

Sesiunea14/pet_adoption_agency/pets/templates/all_pets.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pets</title>
</head>
<body>
{% if pets %}
    <ul>
        {% for pet in pets %}
            <li>
                <a href="{% url 'pets:pet_details' pet.id %}">{{pet}}</a>
            </li>
        {% endfor %}
    </ul>

{% endif %}
{% include "add_pet_form.html" %}
</body>
</html>

Sesiunea14/pet_adoption_agency/pets/templates/error.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error</title>
</head>
<body>
{{error_message}}
</body>
</html>

Sesiunea14/pet_adoption_agency/pets/templates/pet_details.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{pet.name}}</title>
</head>
<body>
{{pet}}
</body>
</html>